# Generated by Django 5.0 on 2024-03-12 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='state',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='pincode_details',
            field=models.ForeignKey(default='000000', on_delete=django.db.models.deletion.PROTECT, to='api.pincodecitystate'),
        ),
    ]
